[default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "2369477168", # Advanced Developer Tools's Workshop ID
    "1779063631", # ZEN
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]